version: "3.8"

services:
  jupyterhub:
    build:
      context: ./jupyterhub
    ports:
      - "8000:8000"
    environment:
      - JUPYTERHUB_CULL_TIMEOUT=600
    volumes:
      - jupyterhub_data:/data
    networks:
      - analytics-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data123
      POSTGRES_DB: analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - analytics-network

  rustfs:
    image: rustfs/rustfs:latest
    environment:
      - RUSTFS_VOLUMES=/data/rustfs0,/data/rustfs1,/data/rustfs2,/data/rustfs3
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - rustfs_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - analytics-network

  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    environment:
      NC_DB_TYPE: postgres
      NC_DB_HOST: postgres
      NC_DB_PORT: 5432
      NC_DB_NAME: analytics
      NC_DB_USER: data
      NC_DB_PASS: data123
    depends_on:
      - postgres
    networks:
      - analytics-network

  prefect:
    image: prefecthq/prefect:2-latest
    environment:
      PREFECT_ORION_DATABASE_CONNECTION_URL: "postgresql://data:data123@postgres:5432/analytics"
      PREFECT_API_URL: "http://prefect:4200/api"
    command: orion start
    ports:
      - "4200:4200"
    networks:
      - analytics-network

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: analytics
      MB_DB_USER: data
      MB_DB_PASS: data123
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - analytics-network

  cube:
    image: cube-js/cube-js:latest
    ports:
      - "4000:4000"
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_USER: data
      CUBEJS_DB_PASS: data123
      CUBEJS_DB_NAME: analytics
    depends_on:
      - postgres
    networks:
      - analytics-network

volumes:
  jupyterhub_data:
  postgres_data:
  rustfs_data:

networks:
  analytics-network:
    driver: bridge
